<?php


namespace App\Http\Controllers;

 
use App\Page;
use App;
use View;
use MetaTag; 

use App\ChargeCommision;
use App\Income;
use App\MemberExtra;
use App\Deposit;
use App\Gateway;
use App\Lib\GoogleAuthenticator;
use App\Transaction;
use App\User;
use Config;
use App\Coins;

use App\Exchange_deposit;

use App\System_Settings;

use App\Exchange_widthdraw;
use App\Exchange_bookings;
use Illuminate\Support\Facades\DB;

 
use App\Http\Controllers\Controller;


use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;


use App\Notifications\Login;


class CoinCls extends Controller
{ 
    
   // private $coin_host="http://164.90.187.159:8080";
 
    private $coin_host="http://167.99.255.217:8080";
    public function __construct( )
    {
         
    
            
            
    }
 
   
  public function wallet_list()
{ 
    
    
    
    //$user_id= Auth::user()->id;
 $data=DB::table('bnext_wallet')->orderBy('id', 'desc')->get()  ;
      
foreach($data as $d)
{
    print_r($d);
    echo "<hr />";    echo "<hr />";    echo "<hr />";
  //echo $d->address;
    echo "<br />";echo "<br />";
 
  try {
 

  // echo "<hr />";   echo "<hr />";   echo "<hr />";   echo "<hr />";
// print_r($d); 

echo "<br />";echo "<br />";
  $b=  $this->balance(  $d->address  ) ;
   print_r($b); echo "<br />";echo "<br />";
  // $this->sendFund(  $d,$b   );
   
   

 
 
 
 } catch (\Throwable $e) { // For PHP 7
   // handle $e
 } catch (\Exception $e) { // For PHP 5
  // handle $e
 }

  
   
  
    
}
    
}
   
   function balance( $address )
    {
        echo $address;
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        
        
$ch = curl_init();

 

curl_setopt($ch, CURLOPT_URL, $this->coin_host.'/operator/'.$address.'/balance');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();


$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch));
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo "BBBBBBBbalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalance--";

 print_r($result);
 echo "-----BBBBBBBbalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalancebalance--";
    return  $result->balance ;

 
    }
   function unspent( $address )
    {
        
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        
        
$ch = curl_init();

 
 
curl_setopt($ch, CURLOPT_URL, $this->coin_host.'/blockchain/transactions/unspent?address='.$address);


curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();


$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);


 
    return  $result ;

 
    }
    
    
    
    
    
    function sendFund( $wallet,$amount )
    {
       $ar=array();
               
 
   $toAddress="117597729deabb7f8364d5576ff2514154c65dba7c6a75fb5ec229a043fb3e76";//$this->request['toAddress'];
  
            echo "...............................";
$ch = curl_init();

$ar=array();


$ar['fromAddress']=  $wallet->address ;//8493dbe495b4112896a5f33e8c43344d14cadf5e267b263f7a4ac3f6cf74bc7d "45d70591c6f0e12693872dc54bf61c1750abde7529b18aa9bcd94e7b3db91073";


$ar['toAddress']=$toAddress;
  
  
$ar["amount"]=  $amount;


$ar["changeAddress"]=$ar['fromAddress']; 

 if($ar['fromAddress'] == $ar['toAddress'])
 
 
 
return "adminwalletadminwalletadminwalletadminwalletadminwallet";



  echo __LINE__."3333333333333333333333<BR /><BR /><BR />";
  
  


 
 print_r($ar);
$json=json_encode($ar);
 


  echo __LINE__."SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS<BR /><BR /><BR />";
  
curl_setopt($ch, CURLOPT_URL,  $this->coin_host.'/operator/wallets/'.$wallet->wallet_id .'/transactions');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);

curl_setopt($ch, CURLOPT_POSTFIELDS, $json );

  echo __LINE__."SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS<BR /><BR /><BR />";

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Accept: application/json';
$headers[] = 'Password: '.$wallet->password ;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);  echo __LINE__."SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS<BR /><BR /><BR />";
print_r($ar);  echo __LINE__."SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS<BR /><BR /><BR />";
print_r($result);
  echo __LINE__."SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS<BR /><BR /><BR />";
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);



$r=array();
   $r['status']=200;
   $r['result']=$result;
  $r['message']="Successfully"; 
    return response()->json($r );
//return $result ;

 
    }
     
    
    
    
}